wandb_version: 1

seed:
  desc: null
  value: 12
debug:
  desc: null
  value: false
model_name:
  desc: null
  value: DCGAN|FirstGan
loss_function:
  desc: null
  value: BCELoss
train_bs:
  desc: null
  value: 8
valid_bs:
  desc: null
  value: 8
img_size:
  desc: null
  value:
  - 512
  - 512
epochs:
  desc: null
  value: 500
lr:
  desc: null
  value: 0.0002
n_accumulate:
  desc: null
  value: 4
device:
  desc: null
  value: cpu
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714392756.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.6
      6: 4.40.0
      8:
      - 1
      - 5
      13: linux-x86_64
